version: '3.8'
services:
  transfer-database:
    image: postgres:16-alpine
    container_name: transfer-database
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: transfer
    ports:
      - 5433:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
